// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `MoniCA.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package atnf.atoms.mon.comms;

public final class DataValuePrxHelper extends Ice.ObjectPrxHelperBase implements DataValuePrx
{
    public static DataValuePrx checkedCast(Ice.ObjectPrx __obj)
    {
        DataValuePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DataValuePrx)
            {
                __d = (DataValuePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    DataValuePrxHelper __h = new DataValuePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DataValuePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        DataValuePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DataValuePrx)
            {
                __d = (DataValuePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    DataValuePrxHelper __h = new DataValuePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DataValuePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DataValuePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    DataValuePrxHelper __h = new DataValuePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DataValuePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        DataValuePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    DataValuePrxHelper __h = new DataValuePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DataValuePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        DataValuePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DataValuePrx)
            {
                __d = (DataValuePrx)__obj;
            }
            else
            {
                DataValuePrxHelper __h = new DataValuePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static DataValuePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DataValuePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            DataValuePrxHelper __h = new DataValuePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::atnf::atoms::mon::comms::DataValue"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _DataValueDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _DataValueDelD();
    }

    public static void __write(IceInternal.BasicStream __os, DataValuePrx v)
    {
        __os.writeProxy(v);
    }

    public static DataValuePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            DataValuePrxHelper result = new DataValuePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
