// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `MoniCA.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package atnf.atoms.mon.comms;

public final class DataValueIntArrayPrxHolder
{
    public
    DataValueIntArrayPrxHolder()
    {
    }

    public
    DataValueIntArrayPrxHolder(DataValueIntArrayPrx value)
    {
        this.value = value;
    }

    public DataValueIntArrayPrx value;
}
