// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `MoniCA.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package atnf.atoms.mon.comms;

public final class dutcarrayHelper
{
    public static void
    write(IceInternal.BasicStream __os, dUTCEntry[] __v)
    {
        if(__v == null)
        {
            __os.writeSize(0);
        }
        else
        {
            __os.writeSize(__v.length);
            for(int __i0 = 0; __i0 < __v.length; __i0++)
            {
                __v[__i0].__write(__os);
            }
        }
    }

    public static dUTCEntry[]
    read(IceInternal.BasicStream __is)
    {
        dUTCEntry[] __v;
        final int __len0 = __is.readAndCheckSeqSize(12);
        __v = new dUTCEntry[__len0];
        for(int __i0 = 0; __i0 < __len0; __i0++)
        {
            __v[__i0] = new dUTCEntry();
            __v[__i0].__read(__is);
        }
        return __v;
    }
}
