// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `MoniCA.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package atnf.atoms.mon.comms;

public class PointDataIce implements java.lang.Cloneable, java.io.Serializable
{
    public String name;

    public long timestamp;

    public DataValue value;

    public boolean alarm;

    public PointDataIce()
    {
    }

    public PointDataIce(String name, long timestamp, DataValue value, boolean alarm)
    {
        this.name = name;
        this.timestamp = timestamp;
        this.value = value;
        this.alarm = alarm;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        PointDataIce _r = null;
        if(rhs instanceof PointDataIce)
        {
            _r = (PointDataIce)rhs;
        }

        if(_r != null)
        {
            if(name != _r.name)
            {
                if(name == null || _r.name == null || !name.equals(_r.name))
                {
                    return false;
                }
            }
            if(timestamp != _r.timestamp)
            {
                return false;
            }
            if(value != _r.value)
            {
                if(value == null || _r.value == null || !value.equals(_r.value))
                {
                    return false;
                }
            }
            if(alarm != _r.alarm)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::atnf::atoms::mon::comms::PointDataIce");
        __h = IceInternal.HashUtil.hashAdd(__h, name);
        __h = IceInternal.HashUtil.hashAdd(__h, timestamp);
        __h = IceInternal.HashUtil.hashAdd(__h, value);
        __h = IceInternal.HashUtil.hashAdd(__h, alarm);
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(name);
        __os.writeLong(timestamp);
        __os.writeObject(value);
        __os.writeBool(alarm);
    }

    private class Patcher implements IceInternal.Patcher
    {
        public void
        patch(Ice.Object v)
        {
            if(v == null || v instanceof DataValue)
            {
                value = (DataValue)v;
            }
            else
            {
                IceInternal.Ex.throwUOE(type(), v);
            }
        }

        public String
        type()
        {
            return "::atnf::atoms::mon::comms::DataValue";
        }
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        name = __is.readString();
        timestamp = __is.readLong();
        __is.readObject(new Patcher());
        alarm = __is.readBool();
    }

    public static final long serialVersionUID = 1166886340670180483L;
}
