// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package atnf.atoms.mon.comms;

// <auto-generated>
//
// Generated from file `MoniCA.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public class PubSubRequest implements java.lang.Cloneable, java.io.Serializable
{
    public String topicname;

    public String[] pointnames;

    public PubSubRequest()
    {
    }

    public PubSubRequest(String topicname, String[] pointnames)
    {
        this.topicname = topicname;
        this.pointnames = pointnames;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        PubSubRequest _r = null;
        try
        {
            _r = (PubSubRequest)rhs;
        }
        catch(ClassCastException ex)
        {
        }

        if(_r != null)
        {
            if(topicname != _r.topicname)
            {
                if(topicname == null || _r.topicname == null || !topicname.equals(_r.topicname))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(pointnames, _r.pointnames))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 0;
        if(topicname != null)
        {
            __h = 5 * __h + topicname.hashCode();
        }
        if(pointnames != null)
        {
            for(int __i0 = 0; __i0 < pointnames.length; __i0++)
            {
                if(pointnames[__i0] != null)
                {
                    __h = 5 * __h + pointnames[__i0].hashCode();
                }
            }
        }
        return __h;
    }

    public java.lang.Object
    clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(topicname);
        stringarrayHelper.write(__os, pointnames);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        topicname = __is.readString();
        pointnames = stringarrayHelper.read(__is);
    }
}
