// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `MoniCA.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package atnf.atoms.mon.comms;

public interface PubSubClientPrx extends Ice.ObjectPrx
{
    public void updateData(PointDataIce[] newdata);

    public void updateData(PointDataIce[] newdata, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateData(PointDataIce[] newdata);

    public Ice.AsyncResult begin_updateData(PointDataIce[] newdata, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateData(PointDataIce[] newdata, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateData(PointDataIce[] newdata, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateData(PointDataIce[] newdata, Callback_PubSubClient_updateData __cb);

    public Ice.AsyncResult begin_updateData(PointDataIce[] newdata, java.util.Map<String, String> __ctx, Callback_PubSubClient_updateData __cb);

    public void end_updateData(Ice.AsyncResult __result);
}
