// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package atnf.atoms.mon.comms;

// <auto-generated>
//
// Generated from file `MoniCA.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public enum DataType implements java.io.Serializable
{
    
    DTNull,
    
    DTFloat,
    
    DTDouble,
    
    DTInt,
    
    DTLong,
    
    DTString,
    
    DTBoolean,
    
    DTAbsTime,
    
    DTRelTime,
    
    DTAngle;

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeByte((byte)ordinal());
    }

    public static DataType
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readByte(10);
        return values()[__v];
    }
}
