// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package atnf.atoms.mon.comms;

// <auto-generated>
//
// Generated from file `MoniCA.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class DataValueFloatArrayPrxHelper extends Ice.ObjectPrxHelperBase implements DataValueFloatArrayPrx
{
    public static DataValueFloatArrayPrx
    checkedCast(Ice.ObjectPrx __obj)
    {
        DataValueFloatArrayPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (DataValueFloatArrayPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA("::atnf::atoms::mon::comms::DataValueFloatArray"))
                {
                    DataValueFloatArrayPrxHelper __h = new DataValueFloatArrayPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DataValueFloatArrayPrx
    checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        DataValueFloatArrayPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (DataValueFloatArrayPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA("::atnf::atoms::mon::comms::DataValueFloatArray", __ctx))
                {
                    DataValueFloatArrayPrxHelper __h = new DataValueFloatArrayPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DataValueFloatArrayPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DataValueFloatArrayPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA("::atnf::atoms::mon::comms::DataValueFloatArray"))
                {
                    DataValueFloatArrayPrxHelper __h = new DataValueFloatArrayPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DataValueFloatArrayPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        DataValueFloatArrayPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA("::atnf::atoms::mon::comms::DataValueFloatArray", __ctx))
                {
                    DataValueFloatArrayPrxHelper __h = new DataValueFloatArrayPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DataValueFloatArrayPrx
    uncheckedCast(Ice.ObjectPrx __obj)
    {
        DataValueFloatArrayPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (DataValueFloatArrayPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                DataValueFloatArrayPrxHelper __h = new DataValueFloatArrayPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static DataValueFloatArrayPrx
    uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DataValueFloatArrayPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            DataValueFloatArrayPrxHelper __h = new DataValueFloatArrayPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    protected Ice._ObjectDelM
    __createDelegateM()
    {
        return new _DataValueFloatArrayDelM();
    }

    protected Ice._ObjectDelD
    __createDelegateD()
    {
        return new _DataValueFloatArrayDelD();
    }

    public static void
    __write(IceInternal.BasicStream __os, DataValueFloatArrayPrx v)
    {
        __os.writeProxy(v);
    }

    public static DataValueFloatArrayPrx
    __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            DataValueFloatArrayPrxHelper result = new DataValueFloatArrayPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }
}
