/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class atnf_atoms_mon_util_MonitorNativeLinux */

#ifndef _Included_atnf_atoms_mon_util_MonitorNativeLinux
#define _Included_atnf_atoms_mon_util_MonitorNativeLinux
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     atnf_atoms_mon_util_MonitorNativeLinux
 * Method:    getCPUTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_atnf_atoms_mon_util_MonitorNativeLinux_getCPUTime
  (JNIEnv *, jclass);

/*
 * Class:     atnf_atoms_mon_util_MonitorNativeLinux
 * Method:    getCPUUserTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_atnf_atoms_mon_util_MonitorNativeLinux_getCPUUserTime
  (JNIEnv *, jclass);

/*
 * Class:     atnf_atoms_mon_util_MonitorNativeLinux
 * Method:    getCPUSystemTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_atnf_atoms_mon_util_MonitorNativeLinux_getCPUSystemTime
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
